---
include:
  - board: technikable
    - cmake-args: -DCONFIG_ZMK_POINTING=y
  - board: technikable@1.1
    - cmake-args: -DCONFIG_ZMK_POINTING=y
  # - board: technikable
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   artifact-name: technikable-1.0-studio
  # - board: technikable@1.1
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   artifact-name: technikable-1.1-studio
